
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tutor-app-frontend
    ports:
      - "3000:3000"   # Localhost:8080 -> Vite
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    command: npm run dev
    depends_on:
      - backend
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tutor-app-backend
    ports:
      - "8000:8000"   # Localhost:8000 -> FastAPI
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    develop:
      watch:
        - path: ./backend
          target: /app
          action: sync
